run:
  go: '1.20'
  issues-exit-code: 1
  timeout: 10m
  modules-download-mode: readonly
  allow-parallel-runners: true
  skip-dirs:
    - .git
    - .docker
    - .bin

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gci
    - gofmt
    - gofumpt
    - goimports
    - govet
    - misspell
    - varcheck
  fast: false
