run:
  go: '1.24.4'
  issues-exit-code: 1
  timeout: 10m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gci
    - gofmt
    - gofumpt
    - goimports
    - govet
    - misspell
    - unused
    - gosec
  fast: false

issues:
  # Restricts maximum count of issues to display with the same text, and show all instead.
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-dirs-use-default: true
  exclude-dirs:
    - .git
    - .docker
    - .bin
  exclude-rules:
  # disabling some linters for test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  # disabling some linters rules
  exclude:
    # gosec
    - G101 # Potential hardcoded credentials
    - G114 # Use of net/http serve function that has no support for setting timeouts
    - G113 # Potential uncontrolled memory consumption in Rat.SetString - this is fixed since go 1.17.7
    - G115 # We do this everywhere (I suppose if it overflows, at least it will for everyone...)
