// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: palomachain/paloma/paloma/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8265cbfb24a07e7a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8265cbfb24a07e7a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryLightNodeClientLicensesResponse struct {
	LightNodeClientLicenses []*LightNodeClientLicense `protobuf:"bytes,1,rep,name=light_node_client_licenses,json=lightNodeClientLicenses,proto3" json:"light_node_client_licenses,omitempty"`
}

func (m *QueryLightNodeClientLicensesResponse) Reset()         { *m = QueryLightNodeClientLicensesResponse{} }
func (m *QueryLightNodeClientLicensesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLightNodeClientLicensesResponse) ProtoMessage()    {}
func (*QueryLightNodeClientLicensesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8265cbfb24a07e7a, []int{2}
}
func (m *QueryLightNodeClientLicensesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLightNodeClientLicensesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLightNodeClientLicensesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLightNodeClientLicensesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLightNodeClientLicensesResponse.Merge(m, src)
}
func (m *QueryLightNodeClientLicensesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLightNodeClientLicensesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLightNodeClientLicensesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLightNodeClientLicensesResponse proto.InternalMessageInfo

func (m *QueryLightNodeClientLicensesResponse) GetLightNodeClientLicenses() []*LightNodeClientLicense {
	if m != nil {
		return m.LightNodeClientLicenses
	}
	return nil
}

type QueryLightNodeClientFeegranterResponse struct {
	LightNodeClientFeegranter *LightNodeClientFeegranter `protobuf:"bytes,1,opt,name=light_node_client_feegranter,json=lightNodeClientFeegranter,proto3" json:"light_node_client_feegranter,omitempty"`
}

func (m *QueryLightNodeClientFeegranterResponse) Reset() {
	*m = QueryLightNodeClientFeegranterResponse{}
}
func (m *QueryLightNodeClientFeegranterResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLightNodeClientFeegranterResponse) ProtoMessage()    {}
func (*QueryLightNodeClientFeegranterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8265cbfb24a07e7a, []int{3}
}
func (m *QueryLightNodeClientFeegranterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLightNodeClientFeegranterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLightNodeClientFeegranterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLightNodeClientFeegranterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLightNodeClientFeegranterResponse.Merge(m, src)
}
func (m *QueryLightNodeClientFeegranterResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLightNodeClientFeegranterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLightNodeClientFeegranterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLightNodeClientFeegranterResponse proto.InternalMessageInfo

func (m *QueryLightNodeClientFeegranterResponse) GetLightNodeClientFeegranter() *LightNodeClientFeegranter {
	if m != nil {
		return m.LightNodeClientFeegranter
	}
	return nil
}

type QueryLightNodeClientFunderResponse struct {
	LightNodeClientFunder *LightNodeClientFunder `protobuf:"bytes,1,opt,name=light_node_client_funder,json=lightNodeClientFunder,proto3" json:"light_node_client_funder,omitempty"`
}

func (m *QueryLightNodeClientFunderResponse) Reset()         { *m = QueryLightNodeClientFunderResponse{} }
func (m *QueryLightNodeClientFunderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLightNodeClientFunderResponse) ProtoMessage()    {}
func (*QueryLightNodeClientFunderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8265cbfb24a07e7a, []int{4}
}
func (m *QueryLightNodeClientFunderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLightNodeClientFunderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLightNodeClientFunderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLightNodeClientFunderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLightNodeClientFunderResponse.Merge(m, src)
}
func (m *QueryLightNodeClientFunderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLightNodeClientFunderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLightNodeClientFunderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLightNodeClientFunderResponse proto.InternalMessageInfo

func (m *QueryLightNodeClientFunderResponse) GetLightNodeClientFunder() *LightNodeClientFunder {
	if m != nil {
		return m.LightNodeClientFunder
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "palomachain.paloma.paloma.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "palomachain.paloma.paloma.QueryParamsResponse")
	proto.RegisterType((*QueryLightNodeClientLicensesResponse)(nil), "palomachain.paloma.paloma.QueryLightNodeClientLicensesResponse")
	proto.RegisterType((*QueryLightNodeClientFeegranterResponse)(nil), "palomachain.paloma.paloma.QueryLightNodeClientFeegranterResponse")
	proto.RegisterType((*QueryLightNodeClientFunderResponse)(nil), "palomachain.paloma.paloma.QueryLightNodeClientFunderResponse")
}

func init() {
	proto.RegisterFile("palomachain/paloma/paloma/query.proto", fileDescriptor_8265cbfb24a07e7a)
}

var fileDescriptor_8265cbfb24a07e7a = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x6b, 0x60, 0x3d, 0x78, 0x37, 0x33, 0xa0, 0x0b, 0x55, 0x60, 0x06, 0xa6, 0x81, 0x20,
	0xa6, 0x1d, 0xd3, 0x98, 0x60, 0xaa, 0x18, 0x62, 0x5c, 0x26, 0x04, 0x3d, 0x70, 0xe0, 0x52, 0xb9,
	0xad, 0x97, 0x46, 0x4a, 0xed, 0x2c, 0x76, 0x10, 0xbb, 0xf2, 0x05, 0x40, 0x20, 0x71, 0xe5, 0x1b,
	0x70, 0xe2, 0xc4, 0x8d, 0xdb, 0x8e, 0x93, 0xb8, 0x70, 0x42, 0xa8, 0xe5, 0x83, 0xa0, 0xd8, 0x6e,
	0xb7, 0xa9, 0x49, 0xbb, 0xec, 0x94, 0x17, 0x3b, 0xff, 0xf7, 0x7e, 0xce, 0xfb, 0x3f, 0xc3, 0x5b,
	0x11, 0x0d, 0x45, 0x9f, 0x76, 0x7a, 0x34, 0xe0, 0xc4, 0xc4, 0xa3, 0xc7, 0x5e, 0xc2, 0xe2, 0x7d,
	0x2f, 0x8a, 0x85, 0x12, 0x68, 0xf1, 0xd8, 0x67, 0x9e, 0x89, 0xed, 0xc3, 0xb9, 0xd3, 0x11, 0xb2,
	0x2f, 0x24, 0x69, 0x53, 0xc9, 0x8c, 0x86, 0xbc, 0xad, 0xb5, 0x99, 0xa2, 0x35, 0x12, 0x51, 0x3f,
	0xe0, 0x54, 0x05, 0x82, 0x9b, 0x34, 0xce, 0x82, 0x2f, 0x7c, 0xa1, 0x43, 0x92, 0x46, 0x76, 0xb5,
	0xea, 0x0b, 0xe1, 0x87, 0x8c, 0xd0, 0x28, 0x20, 0x94, 0x73, 0xa1, 0xb4, 0x44, 0xda, 0xdd, 0xab,
	0x76, 0x57, 0xbf, 0xb5, 0x93, 0x5d, 0xc2, 0xfa, 0x91, 0xb2, 0x5c, 0xce, 0xe3, 0x7c, 0xfc, 0x30,
	0xf0, 0x7b, 0xaa, 0xc5, 0x45, 0x97, 0xb5, 0x3a, 0x61, 0xc0, 0xb8, 0x6a, 0xed, 0x32, 0xe6, 0xc7,
	0x94, 0x2b, 0x16, 0x5b, 0xf5, 0xc3, 0x42, 0xea, 0x84, 0x77, 0xc7, 0xca, 0x8d, 0x22, 0xca, 0x30,
	0xe8, 0x30, 0x2e, 0x99, 0x95, 0x2e, 0xe7, 0x4b, 0x23, 0x1a, 0xd3, 0xbe, 0x3d, 0x37, 0x5e, 0x80,
	0xe8, 0x55, 0xfa, 0x37, 0x5f, 0xea, 0xc5, 0x26, 0xdb, 0x4b, 0x98, 0x54, 0xf8, 0x35, 0xbc, 0x78,
	0x62, 0x55, 0x46, 0x82, 0x4b, 0x86, 0x1a, 0xb0, 0x6c, 0xc4, 0x15, 0x70, 0x1d, 0xac, 0xcc, 0xd7,
	0x97, 0xbc, 0xdc, 0x86, 0x79, 0x46, 0xba, 0x75, 0xe1, 0xe0, 0xcf, 0xb5, 0x52, 0xd3, 0xca, 0xf0,
	0x17, 0x00, 0x6f, 0xea, 0xc4, 0x3b, 0x29, 0xfe, 0x0b, 0xd1, 0x65, 0x4f, 0x35, 0xfc, 0x8e, 0x61,
	0x3f, 0xaa, 0xc4, 0xa1, 0x93, 0x7b, 0xc2, 0xb4, 0xfa, 0xf9, 0x95, 0xf9, 0x7a, 0x6d, 0x4a, 0xf5,
	0xec, 0xfc, 0xcd, 0x2b, 0x61, 0x76, 0x5d, 0xfc, 0x15, 0xc0, 0xe5, 0x2c, 0xb0, 0xed, 0x71, 0x33,
	0xc7, 0x68, 0x09, 0xac, 0x4e, 0x6b, 0xba, 0xfd, 0x35, 0x0f, 0x4e, 0x0f, 0x77, 0xac, 0xc6, 0x62,
	0x98, 0xb7, 0x85, 0x3f, 0x00, 0x88, 0x33, 0x09, 0xb5, 0x61, 0xc6, 0x74, 0x01, 0xac, 0xe4, 0x99,
	0xca, 0x92, 0xdd, 0x2f, 0x40, 0x66, 0x72, 0x5f, 0x0a, 0xb3, 0x96, 0xeb, 0x3f, 0xe7, 0xe0, 0x9c,
	0x26, 0x42, 0x9f, 0x00, 0x2c, 0x9b, 0x7e, 0xa3, 0x7b, 0x53, 0xb2, 0x4f, 0x1a, 0xcd, 0xf1, 0x4e,
	0xfb, 0xb9, 0x39, 0x1e, 0xbe, 0xfd, 0xfe, 0xd7, 0xbf, 0xcf, 0xe7, 0x6e, 0xa0, 0x25, 0x32, 0xcb,
	0xdf, 0xe8, 0x3b, 0x80, 0xce, 0x73, 0xa6, 0x72, 0x9c, 0x86, 0x2e, 0x7b, 0x66, 0xe2, 0xbd, 0xd1,
	0xc4, 0x7b, 0xcf, 0xd2, 0x89, 0x77, 0x1a, 0xb3, 0x88, 0x66, 0x58, 0x17, 0x6f, 0x6a, 0xc4, 0x75,
	0xb4, 0x46, 0xce, 0x30, 0xbd, 0x12, 0xfd, 0x00, 0xb0, 0x3a, 0x89, 0x7d, 0x64, 0x84, 0x5c, 0xf0,
	0x27, 0x05, 0xc1, 0x27, 0xad, 0x8d, 0x1b, 0x1a, 0x7d, 0x03, 0xad, 0x93, 0xb3, 0x5d, 0x78, 0xe8,
	0x1b, 0x80, 0x95, 0x0c, 0x78, 0xed, 0x97, 0x5c, 0xf0, 0xcd, 0xa2, 0xe0, 0x27, 0x1c, 0x8f, 0x1f,
	0x69, 0xe8, 0x35, 0xb4, 0x4a, 0x8a, 0xdf, 0xb3, 0x5b, 0xdb, 0x07, 0x03, 0x17, 0x1c, 0x0e, 0x5c,
	0xf0, 0x77, 0xe0, 0x82, 0x8f, 0x43, 0xb7, 0x74, 0x38, 0x74, 0x4b, 0xbf, 0x87, 0x6e, 0xe9, 0xcd,
	0x5d, 0x3f, 0x50, 0xbd, 0xa4, 0xed, 0x75, 0x44, 0x3f, 0x2b, 0xf1, 0xbb, 0x51, 0xa0, 0xf6, 0x23,
	0x26, 0xdb, 0x65, 0x7d, 0xa6, 0xd5, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x33, 0xdc, 0xf5, 0x11,
	0xe9, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	GetLightNodeClientLicenses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueryLightNodeClientLicensesResponse, error)
	GetLightNodeClientFeegranter(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueryLightNodeClientFeegranterResponse, error)
	GetLightNodeClientFunder(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueryLightNodeClientFunderResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/palomachain.paloma.paloma.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLightNodeClientLicenses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueryLightNodeClientLicensesResponse, error) {
	out := new(QueryLightNodeClientLicensesResponse)
	err := c.cc.Invoke(ctx, "/palomachain.paloma.paloma.Query/GetLightNodeClientLicenses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLightNodeClientFeegranter(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueryLightNodeClientFeegranterResponse, error) {
	out := new(QueryLightNodeClientFeegranterResponse)
	err := c.cc.Invoke(ctx, "/palomachain.paloma.paloma.Query/GetLightNodeClientFeegranter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLightNodeClientFunder(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueryLightNodeClientFunderResponse, error) {
	out := new(QueryLightNodeClientFunderResponse)
	err := c.cc.Invoke(ctx, "/palomachain.paloma.paloma.Query/GetLightNodeClientFunder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	GetLightNodeClientLicenses(context.Context, *emptypb.Empty) (*QueryLightNodeClientLicensesResponse, error)
	GetLightNodeClientFeegranter(context.Context, *emptypb.Empty) (*QueryLightNodeClientFeegranterResponse, error)
	GetLightNodeClientFunder(context.Context, *emptypb.Empty) (*QueryLightNodeClientFunderResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetLightNodeClientLicenses(ctx context.Context, req *emptypb.Empty) (*QueryLightNodeClientLicensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLightNodeClientLicenses not implemented")
}
func (*UnimplementedQueryServer) GetLightNodeClientFeegranter(ctx context.Context, req *emptypb.Empty) (*QueryLightNodeClientFeegranterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLightNodeClientFeegranter not implemented")
}
func (*UnimplementedQueryServer) GetLightNodeClientFunder(ctx context.Context, req *emptypb.Empty) (*QueryLightNodeClientFunderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLightNodeClientFunder not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/palomachain.paloma.paloma.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLightNodeClientLicenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLightNodeClientLicenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/palomachain.paloma.paloma.Query/GetLightNodeClientLicenses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLightNodeClientLicenses(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLightNodeClientFeegranter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLightNodeClientFeegranter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/palomachain.paloma.paloma.Query/GetLightNodeClientFeegranter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLightNodeClientFeegranter(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLightNodeClientFunder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLightNodeClientFunder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/palomachain.paloma.paloma.Query/GetLightNodeClientFunder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLightNodeClientFunder(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "palomachain.paloma.paloma.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetLightNodeClientLicenses",
			Handler:    _Query_GetLightNodeClientLicenses_Handler,
		},
		{
			MethodName: "GetLightNodeClientFeegranter",
			Handler:    _Query_GetLightNodeClientFeegranter_Handler,
		},
		{
			MethodName: "GetLightNodeClientFunder",
			Handler:    _Query_GetLightNodeClientFunder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "palomachain/paloma/paloma/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryLightNodeClientLicensesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLightNodeClientLicensesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLightNodeClientLicensesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LightNodeClientLicenses) > 0 {
		for iNdEx := len(m.LightNodeClientLicenses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LightNodeClientLicenses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryLightNodeClientFeegranterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLightNodeClientFeegranterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLightNodeClientFeegranterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LightNodeClientFeegranter != nil {
		{
			size, err := m.LightNodeClientFeegranter.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLightNodeClientFunderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLightNodeClientFunderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLightNodeClientFunderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LightNodeClientFunder != nil {
		{
			size, err := m.LightNodeClientFunder.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLightNodeClientLicensesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LightNodeClientLicenses) > 0 {
		for _, e := range m.LightNodeClientLicenses {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryLightNodeClientFeegranterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LightNodeClientFeegranter != nil {
		l = m.LightNodeClientFeegranter.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLightNodeClientFunderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LightNodeClientFunder != nil {
		l = m.LightNodeClientFunder.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLightNodeClientLicensesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLightNodeClientLicensesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLightNodeClientLicensesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LightNodeClientLicenses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LightNodeClientLicenses = append(m.LightNodeClientLicenses, &LightNodeClientLicense{})
			if err := m.LightNodeClientLicenses[len(m.LightNodeClientLicenses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLightNodeClientFeegranterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLightNodeClientFeegranterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLightNodeClientFeegranterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LightNodeClientFeegranter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LightNodeClientFeegranter == nil {
				m.LightNodeClientFeegranter = &LightNodeClientFeegranter{}
			}
			if err := m.LightNodeClientFeegranter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLightNodeClientFunderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLightNodeClientFunderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLightNodeClientFunderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LightNodeClientFunder", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LightNodeClientFunder == nil {
				m.LightNodeClientFunder = &LightNodeClientFunder{}
			}
			if err := m.LightNodeClientFunder.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
