// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consensus/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgAddMessagesSignatures struct {
	Creator        string                                       `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SignedMessages []*MsgAddMessagesSignatures_MsgSignedMessage `protobuf:"bytes,2,rep,name=signedMessages,proto3" json:"signedMessages,omitempty"`
}

func (m *MsgAddMessagesSignatures) Reset()         { *m = MsgAddMessagesSignatures{} }
func (m *MsgAddMessagesSignatures) String() string { return proto.CompactTextString(m) }
func (*MsgAddMessagesSignatures) ProtoMessage()    {}
func (*MsgAddMessagesSignatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_a503313a1d71ab6c, []int{0}
}
func (m *MsgAddMessagesSignatures) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddMessagesSignatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddMessagesSignatures.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddMessagesSignatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddMessagesSignatures.Merge(m, src)
}
func (m *MsgAddMessagesSignatures) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddMessagesSignatures) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddMessagesSignatures.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddMessagesSignatures proto.InternalMessageInfo

func (m *MsgAddMessagesSignatures) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddMessagesSignatures) GetSignedMessages() []*MsgAddMessagesSignatures_MsgSignedMessage {
	if m != nil {
		return m.SignedMessages
	}
	return nil
}

type MsgAddMessagesSignatures_MsgSignedMessage struct {
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QueueTypeName string `protobuf:"bytes,2,opt,name=queueTypeName,proto3" json:"queueTypeName,omitempty"`
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	ExtraData     []byte `protobuf:"bytes,4,opt,name=extraData,proto3" json:"extraData,omitempty"`
}

func (m *MsgAddMessagesSignatures_MsgSignedMessage) Reset() {
	*m = MsgAddMessagesSignatures_MsgSignedMessage{}
}
func (m *MsgAddMessagesSignatures_MsgSignedMessage) String() string {
	return proto.CompactTextString(m)
}
func (*MsgAddMessagesSignatures_MsgSignedMessage) ProtoMessage() {}
func (*MsgAddMessagesSignatures_MsgSignedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a503313a1d71ab6c, []int{0, 0}
}
func (m *MsgAddMessagesSignatures_MsgSignedMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddMessagesSignatures_MsgSignedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddMessagesSignatures_MsgSignedMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddMessagesSignatures_MsgSignedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddMessagesSignatures_MsgSignedMessage.Merge(m, src)
}
func (m *MsgAddMessagesSignatures_MsgSignedMessage) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddMessagesSignatures_MsgSignedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddMessagesSignatures_MsgSignedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddMessagesSignatures_MsgSignedMessage proto.InternalMessageInfo

func (m *MsgAddMessagesSignatures_MsgSignedMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgAddMessagesSignatures_MsgSignedMessage) GetQueueTypeName() string {
	if m != nil {
		return m.QueueTypeName
	}
	return ""
}

func (m *MsgAddMessagesSignatures_MsgSignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *MsgAddMessagesSignatures_MsgSignedMessage) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

type MsgAddMessagesSignaturesResponse struct {
}

func (m *MsgAddMessagesSignaturesResponse) Reset()         { *m = MsgAddMessagesSignaturesResponse{} }
func (m *MsgAddMessagesSignaturesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddMessagesSignaturesResponse) ProtoMessage()    {}
func (*MsgAddMessagesSignaturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a503313a1d71ab6c, []int{1}
}
func (m *MsgAddMessagesSignaturesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddMessagesSignaturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddMessagesSignaturesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddMessagesSignaturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddMessagesSignaturesResponse.Merge(m, src)
}
func (m *MsgAddMessagesSignaturesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddMessagesSignaturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddMessagesSignaturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddMessagesSignaturesResponse proto.InternalMessageInfo

type MsgDeleteJob struct {
	Creator       string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	QueueTypeName string `protobuf:"bytes,2,opt,name=queueTypeName,proto3" json:"queueTypeName,omitempty"`
	MessageID     uint64 `protobuf:"varint,3,opt,name=messageID,proto3" json:"messageID,omitempty"`
}

func (m *MsgDeleteJob) Reset()         { *m = MsgDeleteJob{} }
func (m *MsgDeleteJob) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteJob) ProtoMessage()    {}
func (*MsgDeleteJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_a503313a1d71ab6c, []int{2}
}
func (m *MsgDeleteJob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteJob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteJob.Merge(m, src)
}
func (m *MsgDeleteJob) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteJob) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteJob.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteJob proto.InternalMessageInfo

func (m *MsgDeleteJob) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteJob) GetQueueTypeName() string {
	if m != nil {
		return m.QueueTypeName
	}
	return ""
}

func (m *MsgDeleteJob) GetMessageID() uint64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

type MsgDeleteJobResponse struct {
}

func (m *MsgDeleteJobResponse) Reset()         { *m = MsgDeleteJobResponse{} }
func (m *MsgDeleteJobResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteJobResponse) ProtoMessage()    {}
func (*MsgDeleteJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a503313a1d71ab6c, []int{3}
}
func (m *MsgDeleteJobResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteJobResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteJobResponse.Merge(m, src)
}
func (m *MsgDeleteJobResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteJobResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgAddMessagesSignatures)(nil), "volumefi.paloma.consensus.MsgAddMessagesSignatures")
	proto.RegisterType((*MsgAddMessagesSignatures_MsgSignedMessage)(nil), "volumefi.paloma.consensus.MsgAddMessagesSignatures.MsgSignedMessage")
	proto.RegisterType((*MsgAddMessagesSignaturesResponse)(nil), "volumefi.paloma.consensus.MsgAddMessagesSignaturesResponse")
	proto.RegisterType((*MsgDeleteJob)(nil), "volumefi.paloma.consensus.MsgDeleteJob")
	proto.RegisterType((*MsgDeleteJobResponse)(nil), "volumefi.paloma.consensus.MsgDeleteJobResponse")
}

func init() { proto.RegisterFile("consensus/tx.proto", fileDescriptor_a503313a1d71ab6c) }

var fileDescriptor_a503313a1d71ab6c = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x65, 0x0a, 0x79, 0x2f, 0xcc, 0xe3, 0x11, 0x33, 0x51, 0x53, 0x89, 0x69, 0x9a, 0xc6, 0x44,
	0x56, 0x6d, 0x02, 0x4b, 0x57, 0x9a, 0x6e, 0x30, 0xa9, 0x8b, 0xe2, 0xca, 0xdd, 0xd0, 0x5e, 0xcb,
	0x24, 0x6d, 0xa7, 0x76, 0xa6, 0x06, 0xf6, 0x6e, 0xdc, 0xf9, 0x1b, 0xfe, 0x89, 0x4b, 0x96, 0x2e,
	0x0d, 0xfc, 0x84, 0x4b, 0x43, 0xb1, 0x05, 0x89, 0x10, 0xc2, 0xae, 0x3d, 0xf7, 0xcc, 0x39, 0xe7,
	0xde, 0x9b, 0x8b, 0x89, 0xc7, 0x63, 0x01, 0xb1, 0xc8, 0x84, 0x25, 0x47, 0x66, 0x92, 0x72, 0xc9,
	0xc9, 0xc9, 0x23, 0x0f, 0xb3, 0x08, 0xee, 0x99, 0x99, 0xd0, 0x90, 0x47, 0xd4, 0x2c, 0x39, 0xc6,
	0xab, 0x82, 0x55, 0x47, 0x04, 0x97, 0xbe, 0xef, 0x80, 0x10, 0x34, 0x00, 0xd1, 0x67, 0x41, 0x4c,
	0x65, 0x96, 0x82, 0x20, 0x2a, 0xfe, 0xeb, 0xa5, 0x40, 0x25, 0x4f, 0x55, 0xa4, 0xa3, 0x76, 0xdd,
	0x2d, 0x7e, 0x49, 0x88, 0x9b, 0x82, 0x05, 0x31, 0x94, 0xaf, 0x54, 0x45, 0xaf, 0xb6, 0xff, 0x75,
	0x6c, 0x73, 0xa3, 0x95, 0xb9, 0xc9, 0x66, 0x5e, 0xe8, 0xaf, 0x8a, 0xb9, 0x6b, 0xda, 0xad, 0x27,
	0x84, 0x0f, 0xd6, 0x49, 0xa4, 0x89, 0x15, 0xe6, 0xe7, 0xb9, 0x6a, 0xae, 0xc2, 0x7c, 0x72, 0x86,
	0xff, 0x3f, 0x64, 0x90, 0xc1, 0xed, 0x38, 0x81, 0x1b, 0x1a, 0x81, 0xaa, 0xe4, 0x91, 0x7f, 0x82,
	0xe4, 0x14, 0xd7, 0x45, 0xe1, 0xac, 0x56, 0x75, 0xd4, 0x6e, 0xb8, 0x4b, 0x60, 0x5e, 0x85, 0x91,
	0x4c, 0xa9, 0x4d, 0x25, 0x55, 0x6b, 0x8b, 0x6a, 0x09, 0x18, 0x06, 0xd6, 0x37, 0xf5, 0xe0, 0x82,
	0x48, 0xe6, 0x8d, 0x1a, 0x21, 0x6e, 0x38, 0x22, 0xb0, 0x21, 0x04, 0x09, 0xd7, 0x7c, 0xb0, 0x65,
	0x84, 0x3b, 0xe7, 0x8d, 0x16, 0x6e, 0x3d, 0x3b, 0xcf, 0x5b, 0x73, 0x97, 0x80, 0x71, 0x8c, 0x0f,
	0x57, 0xdd, 0x8a, 0x14, 0x9d, 0x4f, 0x84, 0xab, 0x8e, 0x08, 0xc8, 0x33, 0xc2, 0x47, 0xbf, 0xaf,
	0xb6, 0xbb, 0xc7, 0xa2, 0x5a, 0x17, 0x7b, 0x3c, 0x2a, 0x32, 0x11, 0xc0, 0xf5, 0xe5, 0x58, 0xce,
	0xb7, 0x2b, 0x95, 0xc4, 0x96, 0xb5, 0x23, 0xb1, 0xb0, 0xb9, 0xea, 0xbd, 0x4d, 0x35, 0x34, 0x99,
	0x6a, 0xe8, 0x63, 0xaa, 0xa1, 0x97, 0x99, 0x56, 0x99, 0xcc, 0xb4, 0xca, 0xfb, 0x4c, 0xab, 0xdc,
	0x59, 0x01, 0x93, 0xc3, 0x6c, 0x60, 0x7a, 0x3c, 0xb2, 0x16, 0x5a, 0xde, 0x90, 0xb2, 0xf8, 0xfb,
	0xdb, 0x1a, 0x59, 0x2b, 0x97, 0x33, 0x4e, 0x40, 0x0c, 0xfe, 0xe4, 0xd7, 0xd3, 0xfd, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x18, 0xe2, 0xb9, 0x02, 0x53, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	AddMessagesSignatures(ctx context.Context, in *MsgAddMessagesSignatures, opts ...grpc.CallOption) (*MsgAddMessagesSignaturesResponse, error)
	DeleteJob(ctx context.Context, in *MsgDeleteJob, opts ...grpc.CallOption) (*MsgDeleteJobResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AddMessagesSignatures(ctx context.Context, in *MsgAddMessagesSignatures, opts ...grpc.CallOption) (*MsgAddMessagesSignaturesResponse, error) {
	out := new(MsgAddMessagesSignaturesResponse)
	err := c.cc.Invoke(ctx, "/volumefi.paloma.consensus.Msg/AddMessagesSignatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteJob(ctx context.Context, in *MsgDeleteJob, opts ...grpc.CallOption) (*MsgDeleteJobResponse, error) {
	out := new(MsgDeleteJobResponse)
	err := c.cc.Invoke(ctx, "/volumefi.paloma.consensus.Msg/DeleteJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	AddMessagesSignatures(context.Context, *MsgAddMessagesSignatures) (*MsgAddMessagesSignaturesResponse, error)
	DeleteJob(context.Context, *MsgDeleteJob) (*MsgDeleteJobResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AddMessagesSignatures(ctx context.Context, req *MsgAddMessagesSignatures) (*MsgAddMessagesSignaturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMessagesSignatures not implemented")
}
func (*UnimplementedMsgServer) DeleteJob(ctx context.Context, req *MsgDeleteJob) (*MsgDeleteJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJob not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AddMessagesSignatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddMessagesSignatures)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddMessagesSignatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volumefi.paloma.consensus.Msg/AddMessagesSignatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddMessagesSignatures(ctx, req.(*MsgAddMessagesSignatures))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volumefi.paloma.consensus.Msg/DeleteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteJob(ctx, req.(*MsgDeleteJob))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "volumefi.paloma.consensus.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMessagesSignatures",
			Handler:    _Msg_AddMessagesSignatures_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _Msg_DeleteJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consensus/tx.proto",
}

func (m *MsgAddMessagesSignatures) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddMessagesSignatures) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddMessagesSignatures) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignedMessages) > 0 {
		for iNdEx := len(m.SignedMessages) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SignedMessages[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddMessagesSignatures_MsgSignedMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddMessagesSignatures_MsgSignedMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddMessagesSignatures_MsgSignedMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExtraData) > 0 {
		i -= len(m.ExtraData)
		copy(dAtA[i:], m.ExtraData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ExtraData)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.QueueTypeName) > 0 {
		i -= len(m.QueueTypeName)
		copy(dAtA[i:], m.QueueTypeName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.QueueTypeName)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddMessagesSignaturesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddMessagesSignaturesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddMessagesSignaturesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteJob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteJob) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteJob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MessageID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MessageID))
		i--
		dAtA[i] = 0x18
	}
	if len(m.QueueTypeName) > 0 {
		i -= len(m.QueueTypeName)
		copy(dAtA[i:], m.QueueTypeName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.QueueTypeName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteJobResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteJobResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteJobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAddMessagesSignatures) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.SignedMessages) > 0 {
		for _, e := range m.SignedMessages {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgAddMessagesSignatures_MsgSignedMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.QueueTypeName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ExtraData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddMessagesSignaturesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteJob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.QueueTypeName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MessageID != 0 {
		n += 1 + sovTx(uint64(m.MessageID))
	}
	return n
}

func (m *MsgDeleteJobResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAddMessagesSignatures) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddMessagesSignatures: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddMessagesSignatures: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedMessages", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedMessages = append(m.SignedMessages, &MsgAddMessagesSignatures_MsgSignedMessage{})
			if err := m.SignedMessages[len(m.SignedMessages)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddMessagesSignatures_MsgSignedMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSignedMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSignedMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueueTypeName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueueTypeName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtraData = append(m.ExtraData[:0], dAtA[iNdEx:postIndex]...)
			if m.ExtraData == nil {
				m.ExtraData = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddMessagesSignaturesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddMessagesSignaturesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddMessagesSignaturesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteJob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteJob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteJob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueueTypeName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueueTypeName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageID", wireType)
			}
			m.MessageID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteJobResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteJobResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteJobResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
