// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: palomachain/paloma/evm/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/palomachain/paloma/x/valset/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRemoveSmartContractDeploymentRequest struct {
	SmartContractID  uint64            `protobuf:"varint,2,opt,name=smartContractID,proto3" json:"smartContractID,omitempty"`
	ChainReferenceID string            `protobuf:"bytes,3,opt,name=chainReferenceID,proto3" json:"chainReferenceID,omitempty"`
	Metadata         types.MsgMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata"`
}

func (m *MsgRemoveSmartContractDeploymentRequest) Reset() {
	*m = MsgRemoveSmartContractDeploymentRequest{}
}
func (m *MsgRemoveSmartContractDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveSmartContractDeploymentRequest) ProtoMessage()    {}
func (*MsgRemoveSmartContractDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631cfc68eb1fd278, []int{0}
}
func (m *MsgRemoveSmartContractDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveSmartContractDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveSmartContractDeploymentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveSmartContractDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveSmartContractDeploymentRequest.Merge(m, src)
}
func (m *MsgRemoveSmartContractDeploymentRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveSmartContractDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveSmartContractDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveSmartContractDeploymentRequest proto.InternalMessageInfo

func (m *MsgRemoveSmartContractDeploymentRequest) GetSmartContractID() uint64 {
	if m != nil {
		return m.SmartContractID
	}
	return 0
}

func (m *MsgRemoveSmartContractDeploymentRequest) GetChainReferenceID() string {
	if m != nil {
		return m.ChainReferenceID
	}
	return ""
}

func (m *MsgRemoveSmartContractDeploymentRequest) GetMetadata() types.MsgMetadata {
	if m != nil {
		return m.Metadata
	}
	return types.MsgMetadata{}
}

type RemoveSmartContractDeploymentResponse struct {
}

func (m *RemoveSmartContractDeploymentResponse) Reset()         { *m = RemoveSmartContractDeploymentResponse{} }
func (m *RemoveSmartContractDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveSmartContractDeploymentResponse) ProtoMessage()    {}
func (*RemoveSmartContractDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_631cfc68eb1fd278, []int{1}
}
func (m *RemoveSmartContractDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveSmartContractDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoveSmartContractDeploymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoveSmartContractDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSmartContractDeploymentResponse.Merge(m, src)
}
func (m *RemoveSmartContractDeploymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *RemoveSmartContractDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSmartContractDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSmartContractDeploymentResponse proto.InternalMessageInfo

type MsgUploadUserSmartContractRequest struct {
	Metadata         types.MsgMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata"`
	ValAddress       string            `protobuf:"bytes,2,opt,name=val_address,json=valAddress,proto3" json:"val_address,omitempty"`
	Title            string            `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	AbiJson          string            `protobuf:"bytes,4,opt,name=abi_json,json=abiJson,proto3" json:"abi_json,omitempty"`
	Bytecode         string            `protobuf:"bytes,5,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	ConstructorInput string            `protobuf:"bytes,6,opt,name=constructor_input,json=constructorInput,proto3" json:"constructor_input,omitempty"`
}

func (m *MsgUploadUserSmartContractRequest) Reset()         { *m = MsgUploadUserSmartContractRequest{} }
func (m *MsgUploadUserSmartContractRequest) String() string { return proto.CompactTextString(m) }
func (*MsgUploadUserSmartContractRequest) ProtoMessage()    {}
func (*MsgUploadUserSmartContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631cfc68eb1fd278, []int{2}
}
func (m *MsgUploadUserSmartContractRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUploadUserSmartContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUploadUserSmartContractRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUploadUserSmartContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUploadUserSmartContractRequest.Merge(m, src)
}
func (m *MsgUploadUserSmartContractRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgUploadUserSmartContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUploadUserSmartContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUploadUserSmartContractRequest proto.InternalMessageInfo

func (m *MsgUploadUserSmartContractRequest) GetMetadata() types.MsgMetadata {
	if m != nil {
		return m.Metadata
	}
	return types.MsgMetadata{}
}

func (m *MsgUploadUserSmartContractRequest) GetValAddress() string {
	if m != nil {
		return m.ValAddress
	}
	return ""
}

func (m *MsgUploadUserSmartContractRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgUploadUserSmartContractRequest) GetAbiJson() string {
	if m != nil {
		return m.AbiJson
	}
	return ""
}

func (m *MsgUploadUserSmartContractRequest) GetBytecode() string {
	if m != nil {
		return m.Bytecode
	}
	return ""
}

func (m *MsgUploadUserSmartContractRequest) GetConstructorInput() string {
	if m != nil {
		return m.ConstructorInput
	}
	return ""
}

type MsgUploadUserSmartContractResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgUploadUserSmartContractResponse) Reset()         { *m = MsgUploadUserSmartContractResponse{} }
func (m *MsgUploadUserSmartContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUploadUserSmartContractResponse) ProtoMessage()    {}
func (*MsgUploadUserSmartContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_631cfc68eb1fd278, []int{3}
}
func (m *MsgUploadUserSmartContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUploadUserSmartContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUploadUserSmartContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUploadUserSmartContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUploadUserSmartContractResponse.Merge(m, src)
}
func (m *MsgUploadUserSmartContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUploadUserSmartContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUploadUserSmartContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUploadUserSmartContractResponse proto.InternalMessageInfo

func (m *MsgUploadUserSmartContractResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgRemoveUserSmartContractRequest struct {
	Metadata   types.MsgMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata"`
	ValAddress string            `protobuf:"bytes,2,opt,name=val_address,json=valAddress,proto3" json:"val_address,omitempty"`
	Id         uint64            `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgRemoveUserSmartContractRequest) Reset()         { *m = MsgRemoveUserSmartContractRequest{} }
func (m *MsgRemoveUserSmartContractRequest) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveUserSmartContractRequest) ProtoMessage()    {}
func (*MsgRemoveUserSmartContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631cfc68eb1fd278, []int{4}
}
func (m *MsgRemoveUserSmartContractRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveUserSmartContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveUserSmartContractRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveUserSmartContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveUserSmartContractRequest.Merge(m, src)
}
func (m *MsgRemoveUserSmartContractRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveUserSmartContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveUserSmartContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveUserSmartContractRequest proto.InternalMessageInfo

func (m *MsgRemoveUserSmartContractRequest) GetMetadata() types.MsgMetadata {
	if m != nil {
		return m.Metadata
	}
	return types.MsgMetadata{}
}

func (m *MsgRemoveUserSmartContractRequest) GetValAddress() string {
	if m != nil {
		return m.ValAddress
	}
	return ""
}

func (m *MsgRemoveUserSmartContractRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeployUserSmartContractRequest struct {
	Metadata    types.MsgMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata"`
	ValAddress  string            `protobuf:"bytes,2,opt,name=val_address,json=valAddress,proto3" json:"val_address,omitempty"`
	Id          uint64            `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	TargetChain string            `protobuf:"bytes,4,opt,name=target_chain,json=targetChain,proto3" json:"target_chain,omitempty"`
}

func (m *MsgDeployUserSmartContractRequest) Reset()         { *m = MsgDeployUserSmartContractRequest{} }
func (m *MsgDeployUserSmartContractRequest) String() string { return proto.CompactTextString(m) }
func (*MsgDeployUserSmartContractRequest) ProtoMessage()    {}
func (*MsgDeployUserSmartContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631cfc68eb1fd278, []int{5}
}
func (m *MsgDeployUserSmartContractRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeployUserSmartContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeployUserSmartContractRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeployUserSmartContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeployUserSmartContractRequest.Merge(m, src)
}
func (m *MsgDeployUserSmartContractRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeployUserSmartContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeployUserSmartContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeployUserSmartContractRequest proto.InternalMessageInfo

func (m *MsgDeployUserSmartContractRequest) GetMetadata() types.MsgMetadata {
	if m != nil {
		return m.Metadata
	}
	return types.MsgMetadata{}
}

func (m *MsgDeployUserSmartContractRequest) GetValAddress() string {
	if m != nil {
		return m.ValAddress
	}
	return ""
}

func (m *MsgDeployUserSmartContractRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgDeployUserSmartContractRequest) GetTargetChain() string {
	if m != nil {
		return m.TargetChain
	}
	return ""
}

type MsgDeployUserSmartContractResponse struct {
	MsgId uint64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
}

func (m *MsgDeployUserSmartContractResponse) Reset()         { *m = MsgDeployUserSmartContractResponse{} }
func (m *MsgDeployUserSmartContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeployUserSmartContractResponse) ProtoMessage()    {}
func (*MsgDeployUserSmartContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_631cfc68eb1fd278, []int{6}
}
func (m *MsgDeployUserSmartContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeployUserSmartContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeployUserSmartContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeployUserSmartContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeployUserSmartContractResponse.Merge(m, src)
}
func (m *MsgDeployUserSmartContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeployUserSmartContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeployUserSmartContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeployUserSmartContractResponse proto.InternalMessageInfo

func (m *MsgDeployUserSmartContractResponse) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgRemoveSmartContractDeploymentRequest)(nil), "palomachain.paloma.evm.MsgRemoveSmartContractDeploymentRequest")
	proto.RegisterType((*RemoveSmartContractDeploymentResponse)(nil), "palomachain.paloma.evm.RemoveSmartContractDeploymentResponse")
	proto.RegisterType((*MsgUploadUserSmartContractRequest)(nil), "palomachain.paloma.evm.MsgUploadUserSmartContractRequest")
	proto.RegisterType((*MsgUploadUserSmartContractResponse)(nil), "palomachain.paloma.evm.MsgUploadUserSmartContractResponse")
	proto.RegisterType((*MsgRemoveUserSmartContractRequest)(nil), "palomachain.paloma.evm.MsgRemoveUserSmartContractRequest")
	proto.RegisterType((*MsgDeployUserSmartContractRequest)(nil), "palomachain.paloma.evm.MsgDeployUserSmartContractRequest")
	proto.RegisterType((*MsgDeployUserSmartContractResponse)(nil), "palomachain.paloma.evm.MsgDeployUserSmartContractResponse")
}

func init() { proto.RegisterFile("palomachain/paloma/evm/tx.proto", fileDescriptor_631cfc68eb1fd278) }

var fileDescriptor_631cfc68eb1fd278 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0x4f, 0x4f, 0x13, 0x4f,
	0x18, 0xee, 0x96, 0xd2, 0x5f, 0x19, 0x7e, 0x2a, 0x4e, 0x10, 0x4a, 0x8d, 0x05, 0x9a, 0x08, 0x15,
	0xe3, 0x6e, 0x44, 0x2f, 0x60, 0x8c, 0x11, 0x30, 0xb1, 0x24, 0xbd, 0x2c, 0xe1, 0xe2, 0xa5, 0x99,
	0xdd, 0x7d, 0x19, 0xd6, 0xec, 0xec, 0xac, 0x3b, 0xd3, 0x0d, 0xbd, 0xfa, 0x09, 0xf8, 0x06, 0x7e,
	0x05, 0x4d, 0xbc, 0xf9, 0x01, 0xe4, 0x48, 0x3c, 0x79, 0x32, 0x06, 0x12, 0x4d, 0xfc, 0x14, 0xa6,
	0x33, 0x4b, 0xad, 0xb5, 0x5d, 0x88, 0x5e, 0xf4, 0xd4, 0x79, 0x9f, 0x77, 0xa6, 0xfb, 0xbc, 0xcf,
	0xfb, 0x0f, 0xcd, 0x47, 0x24, 0xe0, 0x8c, 0xb8, 0xfb, 0xc4, 0x0f, 0x2d, 0x7d, 0xb6, 0x20, 0x61,
	0x96, 0x3c, 0x30, 0xa3, 0x98, 0x4b, 0x8e, 0x67, 0xfa, 0x2e, 0x98, 0xfa, 0x6c, 0x42, 0xc2, 0x2a,
	0xb3, 0x2e, 0x17, 0x8c, 0x0b, 0x8b, 0x09, 0x6a, 0x25, 0x77, 0xbb, 0x3f, 0xfa, 0x41, 0x65, 0x4e,
	0x3b, 0x5a, 0xca, 0xb2, 0xb4, 0x91, 0xba, 0xa6, 0x29, 0xa7, 0x5c, 0xe3, 0xdd, 0x53, 0x8a, 0x5e,
	0xa7, 0x9c, 0xd3, 0x00, 0x2c, 0x65, 0x39, 0xed, 0x3d, 0x0b, 0x58, 0x24, 0x3b, 0xa9, 0x73, 0x69,
	0x08, 0xbf, 0x84, 0x04, 0x02, 0xa4, 0xe5, 0x72, 0xc6, 0x78, 0xa8, 0xef, 0xd5, 0xbe, 0x18, 0x68,
	0xb9, 0x29, 0xa8, 0x0d, 0x8c, 0x27, 0xb0, 0xc3, 0x48, 0x2c, 0x37, 0x79, 0x28, 0x63, 0xe2, 0xca,
	0x2d, 0x88, 0x02, 0xde, 0x61, 0x10, 0x4a, 0x1b, 0x5e, 0xb4, 0x41, 0x48, 0x5c, 0x47, 0x57, 0x44,
	0xff, 0x8d, 0xc6, 0x56, 0x39, 0xbf, 0x60, 0xd4, 0x0b, 0xf6, 0x20, 0x8c, 0x57, 0xd0, 0x94, 0xfa,
	0xb2, 0x0d, 0x7b, 0x10, 0x43, 0xe8, 0x42, 0x63, 0xab, 0x3c, 0xb6, 0x60, 0xd4, 0x27, 0xec, 0x5f,
	0x70, 0xfc, 0x14, 0x95, 0x18, 0x48, 0xe2, 0x11, 0x49, 0xca, 0x85, 0x05, 0xa3, 0x3e, 0xb9, 0xba,
	0x64, 0x0e, 0xd1, 0x4e, 0x93, 0x37, 0x9b, 0x82, 0x36, 0xd3, 0xdb, 0x1b, 0x85, 0xa3, 0x4f, 0xf3,
	0x39, 0xbb, 0xf7, 0x7a, 0xfd, 0xd2, 0xcb, 0xaf, 0xaf, 0x57, 0x7a, 0xe6, 0x76, 0xa1, 0x64, 0x4c,
	0xe5, 0xed, 0xe2, 0x0e, 0x84, 0x1e, 0xc4, 0xb5, 0x65, 0x74, 0xf3, 0x9c, 0x20, 0x45, 0xc4, 0x43,
	0x01, 0xb5, 0x37, 0x79, 0xb4, 0xd8, 0x14, 0x74, 0x37, 0x0a, 0x38, 0xf1, 0x76, 0x05, 0xc4, 0x3f,
	0x3d, 0x38, 0xd3, 0xa2, 0x9f, 0xb5, 0xf1, 0x27, 0xac, 0xf1, 0x1a, 0x9a, 0x4c, 0x48, 0xd0, 0x22,
	0x9e, 0x17, 0x83, 0x10, 0x4a, 0xd1, 0x89, 0x8d, 0xf2, 0x87, 0xb7, 0x77, 0xa6, 0xd3, 0x1a, 0x78,
	0xac, 0x3d, 0x3b, 0x32, 0xf6, 0x43, 0x6a, 0xa3, 0x84, 0x04, 0x29, 0x82, 0xa7, 0xd1, 0xb8, 0xf4,
	0x65, 0x00, 0xa9, 0xb6, 0xda, 0xc0, 0x73, 0xa8, 0x44, 0x1c, 0xbf, 0xf5, 0x5c, 0xf0, 0x50, 0x09,
	0x3a, 0x61, 0xff, 0x47, 0x1c, 0x7f, 0x5b, 0xf0, 0x10, 0x57, 0x50, 0xc9, 0xe9, 0x48, 0x70, 0xb9,
	0x07, 0xe5, 0x71, 0xe5, 0xea, 0xd9, 0xf8, 0x36, 0xba, 0xea, 0xf2, 0x50, 0xc8, 0xb8, 0xed, 0x4a,
	0x1e, 0xb7, 0xfc, 0x30, 0x6a, 0xcb, 0x72, 0x31, 0x4d, 0xda, 0x0f, 0x47, 0xa3, 0x8b, 0x0f, 0x48,
	0x5d, 0xbb, 0x8f, 0x6a, 0x59, 0x92, 0x69, 0x65, 0xf1, 0x65, 0x94, 0xf7, 0x3d, 0xa5, 0x56, 0xc1,
	0xce, 0xfb, 0x5e, 0xed, 0xbd, 0xa1, 0x94, 0xd6, 0x69, 0xf9, 0xbb, 0x95, 0xd6, 0xd4, 0xc7, 0xce,
	0xa8, 0x0f, 0xc6, 0xff, 0x4d, 0x47, 0xa2, 0xab, 0xe9, 0x9f, 0x8a, 0x04, 0x2f, 0xa2, 0xff, 0x25,
	0x89, 0x29, 0xc8, 0x96, 0x22, 0x91, 0x56, 0xcc, 0xa4, 0xc6, 0x36, 0xbb, 0xd0, 0x60, 0xb0, 0x0f,
	0x54, 0xb2, 0x47, 0xc6, 0x9a, 0x26, 0xfb, 0x1a, 0x2a, 0x32, 0x41, 0x5b, 0xbd, 0x84, 0x8f, 0x33,
	0x41, 0x1b, 0xde, 0xea, 0xbb, 0x02, 0x1a, 0x6b, 0x0a, 0x8a, 0x5f, 0x19, 0xe8, 0x46, 0x66, 0x3f,
	0xe2, 0x47, 0xe6, 0xf0, 0x09, 0x6a, 0x5e, 0x70, 0x5c, 0x55, 0x1e, 0x8e, 0xfa, 0x83, 0x0b, 0xcd,
	0x01, 0x7c, 0x68, 0xa0, 0xd9, 0x11, 0x15, 0x8d, 0xd7, 0x32, 0xb8, 0x65, 0x0f, 0x8e, 0xca, 0xfa,
	0xef, 0x3c, 0x4d, 0x29, 0x05, 0x68, 0x76, 0x44, 0xb3, 0x64, 0x32, 0xca, 0x6e, 0xb0, 0xca, 0x8c,
	0xa9, 0x17, 0x89, 0x79, 0xb6, 0x48, 0xcc, 0x27, 0xdd, 0x45, 0xa2, 0x04, 0x18, 0x91, 0xe5, 0xcc,
	0xcf, 0x65, 0x77, 0x41, 0xa6, 0x00, 0xe7, 0x14, 0xd5, 0xc6, 0xe6, 0xd1, 0x49, 0xd5, 0x38, 0x3e,
	0xa9, 0x1a, 0x9f, 0x4f, 0xaa, 0xc6, 0xe1, 0x69, 0x35, 0x77, 0x7c, 0x5a, 0xcd, 0x7d, 0x3c, 0xad,
	0xe6, 0x9e, 0xdd, 0xa2, 0xbe, 0xdc, 0x6f, 0x3b, 0xa6, 0xcb, 0x99, 0x35, 0x64, 0xf5, 0x1d, 0xe8,
	0xe5, 0xdc, 0x89, 0x40, 0x38, 0x45, 0x15, 0xe7, 0xbd, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7e,
	0x64, 0x83, 0x66, 0xc3, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RemoveSmartContractDeployment(ctx context.Context, in *MsgRemoveSmartContractDeploymentRequest, opts ...grpc.CallOption) (*RemoveSmartContractDeploymentResponse, error)
	// ===== User Smart Contracts =====
	UploadUserSmartContract(ctx context.Context, in *MsgUploadUserSmartContractRequest, opts ...grpc.CallOption) (*MsgUploadUserSmartContractResponse, error)
	RemoveUserSmartContract(ctx context.Context, in *MsgRemoveUserSmartContractRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeployUserSmartContract(ctx context.Context, in *MsgDeployUserSmartContractRequest, opts ...grpc.CallOption) (*MsgDeployUserSmartContractResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RemoveSmartContractDeployment(ctx context.Context, in *MsgRemoveSmartContractDeploymentRequest, opts ...grpc.CallOption) (*RemoveSmartContractDeploymentResponse, error) {
	out := new(RemoveSmartContractDeploymentResponse)
	err := c.cc.Invoke(ctx, "/palomachain.paloma.evm.Msg/RemoveSmartContractDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UploadUserSmartContract(ctx context.Context, in *MsgUploadUserSmartContractRequest, opts ...grpc.CallOption) (*MsgUploadUserSmartContractResponse, error) {
	out := new(MsgUploadUserSmartContractResponse)
	err := c.cc.Invoke(ctx, "/palomachain.paloma.evm.Msg/UploadUserSmartContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveUserSmartContract(ctx context.Context, in *MsgRemoveUserSmartContractRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/palomachain.paloma.evm.Msg/RemoveUserSmartContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeployUserSmartContract(ctx context.Context, in *MsgDeployUserSmartContractRequest, opts ...grpc.CallOption) (*MsgDeployUserSmartContractResponse, error) {
	out := new(MsgDeployUserSmartContractResponse)
	err := c.cc.Invoke(ctx, "/palomachain.paloma.evm.Msg/DeployUserSmartContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RemoveSmartContractDeployment(context.Context, *MsgRemoveSmartContractDeploymentRequest) (*RemoveSmartContractDeploymentResponse, error)
	// ===== User Smart Contracts =====
	UploadUserSmartContract(context.Context, *MsgUploadUserSmartContractRequest) (*MsgUploadUserSmartContractResponse, error)
	RemoveUserSmartContract(context.Context, *MsgRemoveUserSmartContractRequest) (*emptypb.Empty, error)
	DeployUserSmartContract(context.Context, *MsgDeployUserSmartContractRequest) (*MsgDeployUserSmartContractResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RemoveSmartContractDeployment(ctx context.Context, req *MsgRemoveSmartContractDeploymentRequest) (*RemoveSmartContractDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSmartContractDeployment not implemented")
}
func (*UnimplementedMsgServer) UploadUserSmartContract(ctx context.Context, req *MsgUploadUserSmartContractRequest) (*MsgUploadUserSmartContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadUserSmartContract not implemented")
}
func (*UnimplementedMsgServer) RemoveUserSmartContract(ctx context.Context, req *MsgRemoveUserSmartContractRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserSmartContract not implemented")
}
func (*UnimplementedMsgServer) DeployUserSmartContract(ctx context.Context, req *MsgDeployUserSmartContractRequest) (*MsgDeployUserSmartContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployUserSmartContract not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RemoveSmartContractDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveSmartContractDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveSmartContractDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/palomachain.paloma.evm.Msg/RemoveSmartContractDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveSmartContractDeployment(ctx, req.(*MsgRemoveSmartContractDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UploadUserSmartContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUploadUserSmartContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UploadUserSmartContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/palomachain.paloma.evm.Msg/UploadUserSmartContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UploadUserSmartContract(ctx, req.(*MsgUploadUserSmartContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveUserSmartContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveUserSmartContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveUserSmartContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/palomachain.paloma.evm.Msg/RemoveUserSmartContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveUserSmartContract(ctx, req.(*MsgRemoveUserSmartContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeployUserSmartContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeployUserSmartContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeployUserSmartContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/palomachain.paloma.evm.Msg/DeployUserSmartContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeployUserSmartContract(ctx, req.(*MsgDeployUserSmartContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "palomachain.paloma.evm.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemoveSmartContractDeployment",
			Handler:    _Msg_RemoveSmartContractDeployment_Handler,
		},
		{
			MethodName: "UploadUserSmartContract",
			Handler:    _Msg_UploadUserSmartContract_Handler,
		},
		{
			MethodName: "RemoveUserSmartContract",
			Handler:    _Msg_RemoveUserSmartContract_Handler,
		},
		{
			MethodName: "DeployUserSmartContract",
			Handler:    _Msg_DeployUserSmartContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "palomachain/paloma/evm/tx.proto",
}

func (m *MsgRemoveSmartContractDeploymentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveSmartContractDeploymentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveSmartContractDeploymentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.ChainReferenceID) > 0 {
		i -= len(m.ChainReferenceID)
		copy(dAtA[i:], m.ChainReferenceID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChainReferenceID)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SmartContractID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SmartContractID))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *RemoveSmartContractDeploymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveSmartContractDeploymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemoveSmartContractDeploymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUploadUserSmartContractRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUploadUserSmartContractRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUploadUserSmartContractRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConstructorInput) > 0 {
		i -= len(m.ConstructorInput)
		copy(dAtA[i:], m.ConstructorInput)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConstructorInput)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Bytecode) > 0 {
		i -= len(m.Bytecode)
		copy(dAtA[i:], m.Bytecode)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Bytecode)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AbiJson) > 0 {
		i -= len(m.AbiJson)
		copy(dAtA[i:], m.AbiJson)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AbiJson)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgUploadUserSmartContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUploadUserSmartContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUploadUserSmartContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveUserSmartContractRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveUserSmartContractRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveUserSmartContractRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgDeployUserSmartContractRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeployUserSmartContractRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeployUserSmartContractRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TargetChain) > 0 {
		i -= len(m.TargetChain)
		copy(dAtA[i:], m.TargetChain)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TargetChain)))
		i--
		dAtA[i] = 0x22
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgDeployUserSmartContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeployUserSmartContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeployUserSmartContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MsgId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MsgId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRemoveSmartContractDeploymentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SmartContractID != 0 {
		n += 1 + sovTx(uint64(m.SmartContractID))
	}
	l = len(m.ChainReferenceID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Metadata.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *RemoveSmartContractDeploymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUploadUserSmartContractRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Metadata.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AbiJson)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Bytecode)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ConstructorInput)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUploadUserSmartContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgRemoveUserSmartContractRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Metadata.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeployUserSmartContractRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Metadata.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.TargetChain)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeployUserSmartContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgId != 0 {
		n += 1 + sovTx(uint64(m.MsgId))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRemoveSmartContractDeploymentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveSmartContractDeploymentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveSmartContractDeploymentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SmartContractID", wireType)
			}
			m.SmartContractID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SmartContractID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainReferenceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainReferenceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveSmartContractDeploymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveSmartContractDeploymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveSmartContractDeploymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUploadUserSmartContractRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUploadUserSmartContractRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUploadUserSmartContractRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AbiJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AbiJson = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bytecode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bytecode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConstructorInput", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConstructorInput = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUploadUserSmartContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUploadUserSmartContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUploadUserSmartContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveUserSmartContractRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveUserSmartContractRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveUserSmartContractRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeployUserSmartContractRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeployUserSmartContractRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeployUserSmartContractRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeployUserSmartContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeployUserSmartContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeployUserSmartContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgId", wireType)
			}
			m.MsgId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
