// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	storetypes "cosmossdk.io/store/types"
	mock "github.com/stretchr/testify/mock"

	types "github.com/cosmos/cosmos-sdk/types"
)

// TreasuryStore is an autogenerated mock type for the TreasuryStore type
type TreasuryStore struct {
	mock.Mock
}

// TreasuryStore provides a mock function with given fields: ctx
func (_m *TreasuryStore) TreasuryStore(ctx types.Context) storetypes.KVStore {
	ret := _m.Called(ctx)

	var r0 storetypes.KVStore
	if rf, ok := ret.Get(0).(func(types.Context) storetypes.KVStore); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storetypes.KVStore)
		}
	}

	return r0
}

type mockConstructorTestingTNewTreasuryStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewTreasuryStore creates a new instance of TreasuryStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTreasuryStore(t mockConstructorTestingTNewTreasuryStore) *TreasuryStore {
	mock := &TreasuryStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
